kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:
- name: publish
  image: plugins/docker
  settings:
    repo: alinbalutoiu/argocd
    tags: linux-amd64-${DRONE_BRANCH}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

